<h2>Verifications</h2>

<?php

// echo "<pre>";
// print_r($paginator);
		$form = $this->form;
		$form->setAttribute('action', $this->url('verifications', array('controller' => 'index', 'action' => 'index')));
		$form->prepare();
		echo $this->form()->openTag($form);
		// // echo $this->formHidden($form->get('id'));
		// echo $this->formRow($form->get('scan'));
		echo $this->formRow($form->get('serach_by'));
		echo $this->formRow($form->get('from'));
		echo $this->formRow($form->get('to'));
		// // echo $this->formRow($form->get('password'));
		
		// // echo $this->formRow($form->get('rememberme'));
		echo $this->formSubmit($form->get('submit'));
		echo $this->form()->closeTag();

if(!empty($paginator)) { ?>
	<table class="table">
	<tr>
		<th>entry number</th>
		<th>scan</th>
		<th>mrn</th>
		<th>ts</th>
	</tr>
	<?php foreach ($paginator as $row) { ?>
			<tr>
			<td><?php  echo $row->getEntryNumber(); ?></td>
			<td><?php  echo $row->getScan(); ?></td>
			<td><?php  echo $row->getMrn(); ?></td>
			<td><?php  echo $row->getTs(); ?></td>
			</tr>
		<?php } ?>
</table>
<?php }
if(!empty($paginator)) {
echo $this->paginationControl($this->paginator,
                                     'Sliding', // All, Elastic, Jumping, Sliding
                                     'search_pagination.phtml', array('route' => 'verifications/paginator-doctrine')); 
}

?>

<script type="text/javascript">
var j = jQuery.noConflict();
j(document).ready(function(){
    j('#from').datepicker({ dateFormat: 'yy-mm-dd' });
    j('#to').datepicker({ dateFormat: 'yy-mm-dd' });
})
    
</script>