<h2>Verifications</h2>

<?php

// echo "<pre>";
// print_r($this->data);
		$form = $this->form;
		$form->setAttribute('action', $this->url('verifications', array('controller' => 'index', 'action' => 'index')));
		$form->setAttribute('method', 'get');
		$form->prepare();
		echo $this->form()->openTag($form);
		// // echo $this->formHidden($form->get('id'));
		// echo $this->formRow($form->get('scan'));
		echo $this->formRow($form->get('serach_by'));
		echo $this->formRow($form->get('from'));
		echo $this->formRow($form->get('to'));
		// // echo $this->formRow($form->get('password'));
		
		// // echo $this->formRow($form->get('rememberme'));
		echo $this->formSubmit($form->get('submit'));
		echo $this->form()->closeTag();

if(!empty($paginator)) { ?>
	<table class="table">
	<tr>
		<th>entry number</th>
		<th>scan</th>
		<th>mrn</th>
		<th>ts</th>
	</tr>
	<?php foreach ($paginator as $row) { ?>
			<tr>
			<td><?php  echo $row->getEntryNumber(); ?></td>
			<td><?php  echo $row->getScan(); ?></td>
			<td><?php  echo $row->getMrn(); ?></td>
			<td><?php  echo $row->getTs(); ?></td>
			</tr>
		<?php } ?>
</table>

<?php }
if(!empty($paginator)) {
	echo  $this->paginationControl($this->paginator, 'Sliding', 'search_pagination.phtml', array('data' => $this->data));
// echo $this->paginationControl($this->paginator,
//                                      'Sliding', // All, Elastic, Jumping, Sliding
//                                      'search_pagination.phtml',
//                                      'verifications/paginator-doctrine',
//                                      array('data' => $this->data)
                                     
//                                       ); 
}

?>
<div id="container" style="min-width: 400px; height: 400px; margin: 0 auto"></div>
<script type="text/javascript">
// var j = jQuery.noConflict();
$(document).ready(function(){
   $('#from').datepicker({ dateFormat: 'yy-mm-dd' });
    $('#to').datepicker({ dateFormat: 'yy-mm-dd' });

     $('#container').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Monthly Average Rainfall'
            },
            subtitle: {
                text: 'Source: WorldClimate.com'
            },
            xAxis: {
                categories: [
                    'Jan',
                    'Feb',
                    'Mar',
                    'Apr',
                    'May',
                    'Jun',
                    'Jul',
                    'Aug',
                    'Sep',
                    'Oct',
                    'Nov',
                    'Dec'
                ]
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Rainfall (mm)'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: 'Tokyo',
                data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    
            }, {
                name: 'New York',
                data: [83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3]
    
            }, {
                name: 'London',
                data: [48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2]
    
            }, {
                name: 'Berlin',
                data: [42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1]
    
            }]
        });
});


    
</script>